{% set name = "azure-storage-queue" %}
{% set version = "12.1.5" %}
{% set sha256 = "f0f2f4064120c05a0b594cb504321b523cefd47329a047dd885bb30978100180" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - azure-core <2.0.0,>=1.26.0
    - azure-common >=1.1.5
    - azure-storage-common >=1.3.0
    - cryptography >=2.1.4
    - isodate >=0.6.1
    - msrest
    - typing-extensions >=4.0.1

test:
  imports:
    - azure.storage
    - azure.storage.queue
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Azure/azure-storage-python
  license: Apache-2.0
  license_family: Apache
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  summary: 'Microsoft Azure Storage Queue Client Library for Python'

extra:
  recipe-maintainers:
    - xhochy
    - awvwgk
    - tvogels
